spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "root"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: "public"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret:
    key: "thisissecretkeyformypersonalspringbootapp"
  expiration: 86400000

file:
  upload-dir: /Users/leonidsidorov/work/uploads